# Generated by Django 5.2.1 on 2025-11-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bình luận', 'verbose_name_plural': 'Bình luận'},
        ),
    ]
